### ISSUE TITLE
Принцип организации дерева

### ISSUE THREAD

**Issue by VasiliyMatutin** [15PIHSE-DataBase/DataBase#1]
Необходимо разобраться как будет реализована структура данного дерева, как предусмотреть хранение разных типов данных

**Comment by KirillDemochkin** [comment]
Предлагаю сделать упрощенный аналог файловой системы Windows

**Comment by VasiliyMatutin** [comment]
Хорошая идея

**Comment by SergeyBazhmin** [comment]
Void \* на данные + enum для указания типа данных

**Comment by KirillDemochkin** [comment]
Должно сработать

**Comment by Golemtata** [comment]
Можно создать структуру типа:
typedef struct tree{
tree\* father;
tree\* child;
tree\* brother;
int value;
}
father - предок
child - первый ребёнок, дальше изменений не будет. То есть тут будет создаваться подобие очереди. Каждый последующий будет записан как брат, а все остальные данные будут копированы.
brother - ну здесь запишем брата(следующего потомка к предку, если таковы будут).

**Comment by VasiliyMatutin** [comment]
Нужно создать отдельную отдельную структуру для файлов, которые мы будем хранить

**Comment by SergeyBazhmin** [comment]
typedef struct Node
{
    Node \* Father;
    Node \* NextBrother;
        Node \* PreviousBrother
    Node \* Child;
    struct Val 
    {
        void \* Parametr;// значение
        Val \* ValNext;// следующее значение
    }Value;
}Node;

**Comment by VasiliyMatutin** [comment]
А зачем нам ещё одна структура OneLevel?  
Оставим просто тупо два указателя

**Comment by KirillDemochkin** [comment]
Может вместо ее оставить просто два указателя?

**Comment by Golemtata** [comment]
Да, в принципе можно убрать

**Comment by Golemtata** [comment]
struct FILE
{
    void \* Parametr;
    FILE \* NextFile;
}Files;

typedef struct folder
{
    folder \* UpFolder;
    folder \* NextFolder;
    folder \* PreviousFolder;
    folder \* DownFolder;
    FILE\* File;
}folder;

**Comment by Golemtata** [comment]
Вот вариант структуры

**Comment by KirillDemochkin** [comment]
нужно будет следить за текущей папкой, т.к. мы постоянно перемещаемся по дереву

**Comment by KirillDemochkin** [comment]
СО структурой врод еразобрались, закрываю
