### ISSUE TITLE
Удаление папки

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#10]

**Comment by SergeyBazhmin** [comment]
https://github.com/15PIHSE-DataBase/DataBase/blob/Sergey/DataBase.cpp
Вроде работает,но нужны дополнителные тесты и кое-какие доработки

**Comment by VasiliyMatutin** [comment]
Протестили, смершил в master

**Comment by VasiliyMatutin** [comment]
Сергей, приведи пжл завтра структуру в функции к виду общей. Спасибо

**Comment by KirillDemochkin** [comment]
Функция реализована и неоднократно доработана Сергеем
