### ISSUE TITLE
Исправить тип данных

### ISSUE THREAD

**Issue by VasiliyMatutin** [15PIHSE-DataBase/DataBase#103]
Изменить CHAR на STRING везде, где используется данное обозначение(enum, функции и т.д.)

**Comment by ascherdakova** [comment]
Обновила add_value и print_values в папках функций для обеих версий библиотек

**Comment by ascherdakova** [comment]
И в enum для обеих версий, скидываю в мастер

**Comment by ascherdakova** [comment]
- обновила change_value. В общем, все, что нашла.
