### ISSUE TITLE
Организовать дозапись в файл при изменении БД

### ISSUE THREAD

**Issue by VasiliyMatutin** [15PIHSE-DataBase/DataBase#11]
Необходимо решить как будет вестись чтение-запись узлов дерева в файл. Пока вопрос открыт, особенно в части редактирования документа при удалении-добавлении узлов. Напоминаю, нам нужна дозапись, а не перезапись

**Comment by Golemtata** [comment]
то есть free?
Это разве не делается автоматом при перезапуске программы?

**Comment by KirillDemochkin** [comment]
Хороший вопрос, нужно будет изучить и возможно еще подумать над неким сжатием этого файла, в котором будет храниться таблица

**Comment by KirillDemochkin** [comment]
Так же тогда понадобятся функции 
Сохранить 
Загрузить

**Comment by VasiliyMatutin** [comment]
Вооот, а сохранять надо на жёсткий диск

**Comment by VasiliyMatutin** [comment]
Поднимаю вопрос о том, в каком виде будет хранится эта БД? Тип документа

**Comment by SergeyBazhmin** [comment]
да хоть текстовый файл

**Comment by SergeyBazhmin** [comment]
прописываешь туда все элементы и потом восстанавливаешь по файлу

**Comment by SergeyBazhmin** [comment]
только как вот с иерархией сделать пока не знаю

**Comment by VasiliyMatutin** [comment]
Я думал об этом. Не слишком долго?

**Comment by VasiliyMatutin** [comment]
Предлагаю пока поискать информацию по этому вопросу

**Comment by KirillDemochkin** [comment]
согласен с предложением, если кто-то освободится раньше, почитайте

**Comment by Golemtata** [comment]
Думаю уже о сохранении на диске

**Comment by VasiliyMatutin** [comment]
Дозапись оказалась слишком ресурсоемкой и тяжелореализуемой. Отказались в пользу других проектов. Остановились на полной перезаписи после выгрузки БД из ОС. Закрываю таск
