### ISSUE TITLE
Нужны протопипы функций для Документации (СРОЧНО)

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#12]
Пишем сюда прототипы для 5 функций 
Добавление 
Удаление 
Запись 
Чтение 
Поиск

**Comment by VasiliyMatutin** [comment]
FOLDER\* InputTree(FOLDER **currPtr, char *newname) //добавление новой папки

**Comment by ascherdakova** [comment]
void Directory(FOLDER _CurrentF)
FOLDER_ UpStep(FOLDER *CurrentF)

**Comment by KirillDemochkin** [comment]
void goToFolder(char*); //переход в папку, на вход подаем название папки, в которую нужно зайти

char*\* str_split(char*, const char); //выделение названий папок из пути, аргументы: путь, разделитель

void goToPath(char*); //проход по папкам, выделенным из пути, аргументы: путь

**Comment by SergeyBazhmin** [comment]
FOLDER\* DeleteFolders(Node _);// Удаление содержимого текущей папки
FOLDER_ Delete(Node *);//Удаление самой папки

**Comment by ascherdakova** [comment]
первая //распечатed содержимоuj текущей директории
вторая //переход на уровень выше

**Comment by Golemtata** [comment]
void Way(folder*) - распечатка пути к папке;
folder(or void) FindFolder(char* ); - поиск папки по имени

**Comment by Golemtata** [comment]
folder*

**Comment by KirillDemochkin** [comment]
Слава, жду твои прототипы

**Comment by Golemtata** [comment]
//Поиск узла дерева по имени
struct folder\* findfolder(char\* , struct folder\* )

//Выгрузка дерева из файла
struct folder\* scanfile(FILE\* )

**Comment by KirillDemochkin** [comment]
Собрал все протоптипы в один файл
