### ISSUE TITLE
Прерывание ввода

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#15]
Как можно адекватно реализовать прерывание ввода, чтобы программа не висла, если вдруг посреди созданя новой папки мы передумали ее создавать, а программа ждет введения имени папки, то же смаое и для поиска и для перехода в папку

**Comment by VasiliyMatutin** [comment]
Да, здесь напрашивается аппаратное прерывание, но это не ассемблер:(

**Comment by VasiliyMatutin** [comment]
Отказались от реализации в пользу более приоритетных задач
