### ISSUE TITLE
Унификация фунуций

### ISSUE THREAD

**Issue by VasiliyMatutin** [15PIHSE-DataBase/DataBase#20]
Вид структуры у всех должен прийти к следующему виду:

typedef enum TYPE
{
    None,
    Int,
    Float,
    Double,
    Bool,
    Character
}TYPE;

typedef struct keys
{
    // TYPE type = None;
    union
    {
        int Integer;
        float Float;
        double Double;
        bool Bool;
        char Character;
    }Value;
    struct keys\* NextKey;
}KEYS;

typedef struct folder
{
    char\* FolderName;
    int level;
    struct folder\* UpFolder;
    struct folder\* PreviousFolder;
    struct folder\* NextFolder;
    struct folder\* DownFolder;
    struct keys \* Values;
}FOLDER;

Также выносим всё, что для работы с клиентом в отдельные ф-ии

**Comment by Golemtata** [comment]
может название структуры с маленькой сделаем в начале?
Ну тип struct keys
Мне просто говорили, что выглядеть должно так... ПРосто вдруг из-за этого проблемы возникнут, не уверен
typedef struct name
{
...
}NAME;

**Comment by Golemtata** [comment]
Если нет с этим проблем, то оставляем

**Comment by VasiliyMatutin** [comment]
Свою функцию обновил

**Comment by ascherdakova** [comment]
Обновите файл проекта под эту структуру, чтобы там сразу это было, будет удобнее

**Comment by ascherdakova** [comment]
А то там предыдущий вариант до сих пор

**Comment by VasiliyMatutin** [comment]
Обновил

**Comment by KirillDemochkin** [comment]
В связи с полным изменением структуры и архитектуры приложения закрываю
