### ISSUE TITLE
Запись ключа в существующий узел/хранение ключей

### ISSUE THREAD

**Issue by VasiliyMatutin** [15PIHSE-DataBase/DataBase#21]
Реализовать функцию добавления или создания нового ключа в union при работе с виртуальной копией базы данных

Обдумать способ хранения и дозаписи ключей в txt файле

**Comment by KirillDemochkin** [comment]
в связи с изменением терминологии, данная задача потеряла актуальность

**Comment by KirillDemochkin** [comment]
Добавить спецификатор

**Comment by VasiliyMatutin** [comment]
Спецификатор добавлен. См stdafx
