### ISSUE TITLE
Подготовка к предрелизу

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#22]
~~1) Собрать прототипы в DataBase.h файл (Кирилл)~~
2) Продумать возможность сбора *.c файлов с функциями в одну библиотеку (Кирилл)
3) Протестировать совместимость функций друг с другом (баги отправить на доработку) (Алина)
4) Реализовать демонстрационную модель БД с использованием функций записи и чтения в файл, добавления и удаления вершин из дерева БД, поиск необходимой вершины в БД по имени (Алина)

**Comment by Golemtata** [comment]
findfolder(char* , struct folder* )

**Comment by Golemtata** [comment]
//Поиск узла дерева по имени
struct folder* findfolder(char* , struct folder* )

//Выгрузка дерева из файла
struct folder* scanfile(FILE* )

**Comment by KirillDemochkin** [comment]
Перенес 5й пункт в 21 таск

**Comment by KirillDemochkin** [comment]
1 сделал, файл назуваетс pi15db.h

**Comment by KirillDemochkin** [comment]
для второго не совсем понятно, т.е. похоже просто все функции в один cpp и h файлы и все
либо можно попробовать .a файл сделать для статичной библиотеки, но пока не понятно как.

**Comment by KirillDemochkin** [comment]
Для пункта 2 нужно будет создать .obj файлы для наших функций и склеить их все в одну библиотеку

**Comment by KirillDemochkin** [comment]
Насколько принципиально для нас делать библиотеку на чистом си? т.к. пока что мне попадается документация в основном для c++
http://stackoverflow.com/questions/13218824/how-to-write-a-dll-file-in-c

**Comment by VasiliyMatutin** [comment]
Желательно, конечно на чистом Си, так как мы все подгоняем  под это

**Comment by KirillDemochkin** [comment]
После дальнейшего изучения, понял, что вообще нормальная тема, просто наш .h файл, в котором #include все остальные .h нашх функций, поэтому нужно уточнить у Павла насчет того, что он подразумевал под библиотекой
edit:
так организованы стандратные библиотеки вроде stdlib.h итд

**Comment by VasiliyMatutin** [comment]
Хорошо, тогда уточните у него в пн пжл этот вопрос

**Comment by VasiliyMatutin** [comment]
Но если так собраны стандартные библиотеки, то берем их за образец, вопросов нет

**Comment by KirillDemochkin** [comment]
прдерелиз был подготовлен, но не удовлетворил заказчика из-за недостатка функционала
