### ISSUE TITLE
Придумать больше функций для работы с базой данных

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#37]

**Comment by KirillDemochkin** [comment]
Функция для удаления всех значений из узла

**Comment by KirillDemochkin** [comment]
функция для вывода всех значений из узла

**Comment by KirillDemochkin** [comment]
изменение значения для данного ключа

**Comment by VasiliyMatutin** [comment]
-функция определения узла значения по ключу
-copypaste значений (пока под вопросом)

**Comment by VasiliyMatutin** [comment]
1 взял, сделал, нужно тестить
2 насколько я понял сделала Алина
3 взял, сделал, нужно тестить
4 нужно улучшение в функции поиска значения по всем узлам
5 взял.

**Comment by KirillDemochkin** [comment]
4 наверное я возьму, т.к. функция поиска была моя

**Comment by KirillDemochkin** [comment]
это таски на завтра, так что пока не торопитесь

**Comment by KirillDemochkin** [comment]
функция обмена значениями двух ключей

**Comment by KirillDemochkin** [comment]
функция вывода всех значений определенного типа из узла

**Comment by KirillDemochkin** [comment]
функция удаления всех значений определенного типа из узла

**Comment by KirillDemochkin** [comment]
функция перемещения значения с его ключом в другой узел

**Comment by ascherdakova** [comment]
"функция вывода всех значений определенного типа из узла"
может модифицировать вывод всех значений? добавить параметр с типом, если all, то выводить все, а если конкретный, то конкретный?

**Comment by ascherdakova** [comment]
Я пока начну это, но жду вашего ответа

**Comment by ascherdakova** [comment]
Тогда может стоит вернуть в enum None, чтобы это было вариантом для вывода всех значений

**Comment by ascherdakova** [comment]
Хотя нет.. пожалуй, лучше написать отдельную функцию

**Comment by ascherdakova** [comment]
В общем, жду вашего мнения

**Comment by ascherdakova** [comment]
Пока я сделала функцию, для которой поступает кроме указателя тип выводимого значения (добавила у себя в enum ALL), а сама функция возвращает количество значений требуемого типа в узле

**Comment by ascherdakova** [comment]
"функция перемещения значения с его ключом в другой узел"
это комбинация поиск+удаление+добавление
отдельную функцию прописывать для этого?

**Comment by VasiliyMatutin** [comment]
Не совсем. Я взял функцию перемещения

**Comment by VasiliyMatutin** [comment]
Так как ты при удалении удалишь ключ, а при добавлении твоя функция добавления выдаст новый, нам же нужно именно перемещение

**Comment by ascherdakova** [comment]
Функции вывода и удаления всех значений определенного типа из узла - это частные случаи моей функции вывода всех значений и Васиной по удалению всех значений. Мы просто доведём наши функции до универсальности. Моя уже в мастере.

**Comment by VasiliyMatutin** [comment]
Пройдусь по всем:
1. Функция для удаления всех значений из узла -- выполнена мной
2. Функция для вывода всех значений из узла -- выполнена Алиной
3. Изменение значения для данного ключа -- выполнена мной
4. Функция определения узла значения по ключу -- для этого Кириллом реализована функция поиск по ключу
5. copypaste значений -- выполнена мной
6. Функция обмена значениями двух ключей -- нет смысла в реализации. Два вырезать-вставить. В крайнем случае переименование
7. Функция вывода всех значений определенного типа из узла - частный случай 2
8. Функция удаления всех значений определенного типа из узла - частный случай 1
9. Функция перемещения значения с его ключом в другой узел -- частный случай 5
