### ISSUE TITLE
Описать точную модель ключа (СРОЧНО)

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#38]
Нужно как можно быстрее описать как будет выглядет у нас ключ (int), сколько цифр итд

**Comment by Golemtata** [comment]
Пока это будет некий неповторяющийся int.
Реализация через глобальную переменную.
Из-за ключа требуется переделать функции удааления(добавление в массив освободившихся ключей), добавление(присвоение нового ключа), выгрузка дерева из файла(присвоение каждому элементу нового уникального ключа).
Могу реализовать функции генерации и освобождения ключа

**Comment by KirillDemochkin** [comment]
Вопрос, а почему реализация через глобальную переменную? если у нас много ключей и они все уникальные для каждого значения

**Comment by KirillDemochkin** [comment]
Слава, назначил тебе  #35 таск

**Comment by Golemtata** [comment]
нужно запоминать предыдущий номер

**Comment by KirillDemochkin** [comment]
модеь описана, так что пока закрываю

**Comment by KirillDemochkin** [comment]
Возник вопрос, а что за массив со свободными ключами, т.е. если у нас количество уникальных ключей привязано к диапазону значений инт, то не будем же мы хранить все свободные значения?

**Comment by KirillDemochkin** [comment]
может наоборот хранить все занятые ключи?

**Comment by Golemtata** [comment]
Массив своодных ключей нужен при удалении. То есть при удалении вершины в этот массив будут записаны все освободившиеся ключи. Стоит так заморачиваться или просто забить?

**Comment by KirillDemochkin** [comment]
Добавить спецификатор

**Comment by VasiliyMatutin** [comment]
Модель описана и закреплена в stdafx на мастере
