### ISSUE TITLE
Изменения терминология. Новые обозначения для структуруы.

### ISSUE THREAD

**Issue by Golemtata** [15PIHSE-DataBase/DataBase#39]
typedef enum TYPE
{
INT,
FLOAT,
DOUBLE,
CHAR
}TYPE;

typedef struct value
{
 TYPE type;
 char \* Value;
 int key;
 struct value\* NextValue;
}VALUE;

typedef struct node
{
char NodeName[255];
int key;
struct node \* UpNode;
struct node \* PreviousNode;
struct node \* NextNode;
struct node \* DownNode;
struct value \* Values;
}NODE;

**Comment by KirillDemochkin** [comment]
все обновили структуру, так что закрываю до дольнейших изменений
