### ISSUE TITLE
Изменение параметров для данного значения

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#49]

**Comment by VasiliyMatutin** [comment]
Выполнил
https://github.com/15PIHSE-DataBase/DataBase/blob/Vasily/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D0%B4%D0%BB%D1%8F%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D1%81%D0%BE%20%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8/ChangeValue.c
