### ISSUE TITLE
Спецификатор и адрес в функциях

### ISSUE THREAD

**Issue by VasiliyMatutin** [15PIHSE-DataBase/DataBase#56]
Рассмотреть возможность и необходимость передачи в функцию спецификатора, а не адреса для работы с узлом/значением

**Comment by KirillDemochkin** [comment]
есть ли смысл в этом, если с помощью функции поиска в узле, можно получить адресс нужного элемента, т.е. например функция удаления значения по спецификатору будет комбинацией функции поиска и удаления по адрессу
