### ISSUE TITLE
Собрать все функции для тестовой библиотеки/Прикрутить эту библиотеку к Демо2.0

### ISSUE THREAD

**Issue by VasiliyMatutin** [15PIHSE-DataBase/DataBase#58]
Сборка в obj файл функций. Для возможности линковки и т.п.

**Comment by KirillDemochkin** [comment]
gcc -g -O -c filename.c
такая команда в gcc соберет нам объектный файл для функции с именем filename.c

чтобы слинковать file1.о и fajl2.o:
$ gcc -o output file1.o file2.o

**Comment by KirillDemochkin** [comment]
(Все лежит в моей ветке)
Не смог сегодня подключить Библиотеку(Прошу прощения, старался, как мог, не уверен, почему проект не собирается(Скорее всего из-за того, что у меня не было доступа к .h файлу от библиотеки), т.к. тестовый проект, в который библиотека была добавлена таким образом собрать удалось (test2), возможно он не будет работать, т.к. все пути к файлам прописаны для моего компа)

Постараюсь как можно более подробно описать процесс подключения библиотеки .lib для использования в проекте:

1)  Правый клик на наш проект, properties, выбераем в верхнем левом углу all configurations

2 )В том же меню с левой стороны выбираем c/c++ -> General(первый пункт в списке) -> Additional Include Directories(Первый пункт в правой части окна)

3) Кликаем туда, выбираем edit, и указываем папку, где лежит наш Header от библиотеки

4) дальше идем в Linker->Input(второй сверху) -> Additional dependencies(Первый пункт)

5)  Кликаем туда, выбираем edit и пишем название нашей библиотеки с расширением .lib

6) Идем в Linker->General-> Additional Library Directories(9 пункт сверху)

7)Кликаем туда, выбираем edit и выбираем папку, в которой лежит сам .lib файл библиотеки

8) Чтобы Использовать библиотеку в коде, нужно в main добавить #include "libraryHeader.h" (т.е. просто инклюдим, те хедеры из библиотеки, которые нам нужны)

Еще раз Прошу прощения, что не собрал полностью проект, но надеюсь пошаговое описание достаточно понятное.

Чтобы непосредственно создать библиотеку нужно просто создать проект в Студио и на второй страничке создания выбрать static library затем там можно создать всякие разные файлы, хеддеры итд, важно, чтобы хеддеры лежали в одном месте. Затем просто нажимаем Билд и берем .lib файл из папки Debug
