### ISSUE TITLE
Переход по папкам

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#6]
Пользователь вводит путь и переходит в нужную папку

**Comment by KirillDemochkin** [comment]
По поводу перехода, пока что вижу для себя такую систему:
есть функция, которая ищет папку на данном уровне и переходит в нее и есть функция, которая контроллирует первую функцию и выполняется до тех пор, пока не будет пройден весь путь

**Comment by KirillDemochkin** [comment]
мне кажется, есть смысл здесь пользоваться функцией поиска папки, т.е. я пока просто оставлю там псевдокод вместо самой функции

**Comment by KirillDemochkin** [comment]
сделал первую версию перехода по пути, пока что не тестировал, функция strtok разбивает строку на подстроки, разделенные "/"

**Comment by KirillDemochkin** [comment]
https://github.com/15PIHSE-DataBase/DataBase/blob/Kirill/DBOrganizationProject/DBOrganizationProject/Kirill.h

https://github.com/15PIHSE-DataBase/DataBase/blob/Kirill/DBOrganizationProject/DBOrganizationProject/Kirill.cpp

**Comment by VasiliyMatutin** [comment]
Смершил с master
