### ISSUE TITLE
Добавление новых папок

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#7]
В конкретной папке пользователь может создать новую папку

**Comment by VasiliyMatutin** [comment]
Так, у меня вопрос по именам
Какие ограничения должны быть? 
Понятно что убираем \
Что ещё?

**Comment by KirillDemochkin** [comment]
Буквы и цифры

**Comment by KirillDemochkin** [comment]
Без пробелов

**Comment by ascherdakova** [comment]
Вообще никаких символов кроме букв и цифр? может нижнее подчёркивание, тире и точку оставить?

**Comment by VasiliyMatutin** [comment]
А чем тебя пробел не устроил?

**Comment by VasiliyMatutin** [comment]
И вообще я бы убрал только то, что мы используем и это / для разделения веток. А в остальном пусть пользователь резвится. Какая разница-то?

**Comment by ascherdakova** [comment]
может взять как в винде? такие же ограничения

**Comment by ascherdakova** [comment]
звёздочки там, стрелки, а всё остальное разрешим

**Comment by VasiliyMatutin** [comment]
Ну в винде они там какую-то нагрузку несут, а нам-то всё-равно

**Comment by KirillDemochkin** [comment]
Хорошо, согласен с вами, давайте тогда все кроме / ?

**Comment by VasiliyMatutin** [comment]
Хорошо, если что-то ещё будет нужно, то я напишу ограничение

**Comment by VasiliyMatutin** [comment]
Ещё вопрос, Кирилл, мне после вставки указатель перекидывать на новую папку или оставаться в текущей директории?

**Comment by KirillDemochkin** [comment]
Мне кажется, в той же папке лучше оставаться

**Comment by VasiliyMatutin** [comment]
Ок

**Comment by VasiliyMatutin** [comment]
Написал функцию. Прошу протестить. Пока не реализовано ограничение на создание одинаковых имён, но уже вполне можете пользоваться для заполнения деревьев 
https://github.com/15PIHSE-DataBase/DataBase/blob/Vasily/DBOrganizationProject/DBOrganizationProject/InputFolder.cpp

**Comment by Golemtata** [comment]
Одинаковые имена могут быть, но не в одной директории

**Comment by VasiliyMatutin** [comment]
Ну я над этим и работаю
Добавление же идёт только в одной директории

**Comment by Golemtata** [comment]
угу, понял

**Comment by VasiliyMatutin** [comment]
Оттестили, смершил с master
