### ISSUE TITLE
Итоговая сборка API

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#73]
В ближайшие несколько дней буду собирать все финальные версии функций в одну библиотеку

**Comment by KirillDemochkin** [comment]
скидываем все функции в NewFunctions в мастере

**Comment by KirillDemochkin** [comment]
15PIDataBaseAPI.lib v1.0

[DataBase.zip](https://github.com/15PIHSE-DataBase/DataBase/files/364521/DataBase.zip)

**Comment by VasiliyMatutin** [comment]
Пересобрать библиотеку и подготовить её для релиза

**Comment by KirillDemochkin** [comment]
Соберу ее как только закончатся все изменения с функциями

**Comment by KirillDemochkin** [comment]
собрал
