### ISSUE TITLE
Вернуться на уровень вверх

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#8]
из данной папки вернуться в предыдущую папку - предок

**Comment by ascherdakova** [comment]
https://github.com/15PIHSE-DataBase/DataBase/blob/Alina/DBOrganizationProject/DBOrganizationProject/UpStep.cpp
Функция готова

**Comment by VasiliyMatutin** [comment]
ф-ия в master
