### ISSUE TITLE
Исправление функции InputTree

### ISSUE THREAD

**Issue by ascherdakova** [15PIHSE-DataBase/DataBase#82]
- Изменить аргумент - указатель функции на проверку повтора имени в узле
- По возможности предусмотреть случаи неверной подачи нулевого указателя, чтобы не происходило создание новых нежелательных корней
- Переместить проверку на повтор имени на вход функции

**Comment by VasiliyMatutin** [comment]
-Исправил
-Данный случай не является неверным, об этом будет отдельно указано в документации
-Исправил
