### ISSUE TITLE
Простой клиент для работы с бд

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#87]

**Comment by KirillDemochkin** [comment]
Загружу сразу минимальную рабочую версию, т.к. частями выкладывать невижу смысла (ориентировочно ВС вечер в моем времени)

**Comment by KirillDemochkin** [comment]
Доделал Клиент 1.0, проект в мастере
извините, что с опозданием

**Comment by VasiliyMatutin** [comment]
Исправить баг с чтением-записью и доработать клиент

**Comment by KirillDemochkin** [comment]
Клиент 1.3 в мастере (Пожалуйста не удаляйте больше его оттуда :D)
