### ISSUE TITLE
Распечатка директории

### ISSUE THREAD

**Issue by KirillDemochkin** [15PIHSE-DataBase/DataBase#9]
Распечатывает все вложенные папки на уровне

**Comment by KirillDemochkin** [comment]
здесь еще неплохо было бы добавить пометку, что из распечатанного файлы, а что папки

**Comment by VasiliyMatutin** [comment]
Но мы пока файлами не занимаемся

**Comment by ascherdakova** [comment]
Тогда когда файлами начнём заниматься, я добавлю если что

**Comment by ascherdakova** [comment]
пробная версия готова, распечатывает содержимое папки, но учитывает только папки
с файлами что-нибудь делать сейчас?

**Comment by KirillDemochkin** [comment]
пока что нет

**Comment by ascherdakova** [comment]
тогда готово
https://github.com/15PIHSE-DataBase/DataBase/blob/Alina/DBOrganizationProject/DBOrganizationProject/Directory.cpp

**Comment by VasiliyMatutin** [comment]
ф-ия в master
